### ISSUE TITLE
auvidea j140 board installation question

### ISSUE THREAD

**Issue by eric-lmi** [InES-HPMM/Lontium_lt6911uxc#2]
Trying the get this driver working with auvidea j140 + B112 HDMI to CSI-2 Bridge. Downloaded j140 latest firmware and had a look in kernel_src. Looks the LT6911 driver source already exist in the right folder. And Makefile and KConfig file has included LT6911 configurations.

Does this mean I only need to decompile the dtb on client side( not on the host and reflash, can I do this on the jetson client side) and add LT6911 parameters. Compile it override the existing dtb?

**Comment by Launchpad-McQ** [comment]
Just a heads up: Ive got the B112 from auvidea and I've been in contact with Lontium and auvidea in order to get the correct firmware to upload to the converter (auvidea instructed me that it is shipped without a firmware flashed). Ive gotten good support from lontium, but auvidea has not been helpful at all. Basically they sold me a paperweight since they aren't supplying the necessary information/documentation about the hardware. I can say that I wont be dealing with auvidea in the future.

**Comment by alegroo** [comment]
Dear All,
yes, in first place the LT6911 needs to be programmed. We are preparing an upload to this repo, to provide the firmware, which was tested on our custom board. Also we will provide a firmware tool for that.
But this will take some time

**Comment by benlypan** [comment]
@alegroo 
I'm looking for the firmware. Could you upload the firmware now?😄

**Comment by cizerpat** [comment]
@benlypan 
I'm sorry, we will not be able to upload the firmware for the LT6911. I suggest you to contact Lontium Semiconductor in this regard.
